// Generated by tools.model_dataset.continuation_contract; do not edit.
#ifndef MODEL_CONTINUATION_CANDLE_STATE_MQH
#define MODEL_CONTINUATION_CANDLE_STATE_MQH

void CandleContinuationState()
{
  ModelContinuationState("CANDLE_CONTROL", "0", "g_candle_magic", "INT", ModelInteger((long)g_candle_magic));
  ModelContinuationState("CANDLE_CONTROL", "0", "g_candle_last_time", "INT", ModelInteger((long)g_candle_last_time));
  ModelContinuationState("CANDLE_CONTROL", "0", "g_macro_seconds", "INT", ModelInteger((long)g_macro_seconds));
  ModelContinuationState("CANDLE_CONTROL", "0", "g_micro_seconds", "INT", ModelInteger((long)g_micro_seconds));
  ModelContinuationState("CANDLE_CONTROL", "0", "g_candle_sequence", "INT", ModelInteger((long)g_candle_sequence));
  ModelContinuationState("CANDLE_CONTROL", "0", "g_last_micro_bar", "INT", ModelInteger((long)g_last_micro_bar));
  ModelContinuationState("CANDLE_CONTROL", "0", "g_candle_stopping", "BOOL", ModelBoolean(g_candle_stopping));
  ModelContinuationState("CANDLE_CONTROL", "0", "g_candle_tester_interval_completed", "BOOL", ModelBoolean(g_candle_tester_interval_completed));
  ModelContinuationState("CANDLE_CONTROL", "0", "g_candle_broker_count", "INT", ModelInteger((long)g_candle_broker_count));
  ModelContinuationState("CANDLE_CONTROL", "0", "g_candle_virtual_count", "INT", ModelInteger((long)g_candle_virtual_count));
  ModelContinuationState("CANDLE_CONTROL", "0", "g_candle_broker_extent", "INT", ModelInteger((long)g_candle_broker_extent));
  ModelContinuationState("CANDLE_CONTROL", "0", "g_candle_virtual_extent", "INT", ModelInteger((long)g_candle_virtual_extent));
  ModelContinuationState("CANDLE_CONTROL", "0", "g_candle_broker_peak", "INT", ModelInteger((long)g_candle_broker_peak));
  ModelContinuationState("CANDLE_CONTROL", "0", "g_candle_virtual_peak", "INT", ModelInteger((long)g_candle_virtual_peak));
  ModelContinuationState("CANDLE_CONTROL", "0", "g_candle_broker_uncertain", "BOOL", ModelBoolean(g_candle_broker_uncertain));
  ModelContinuationState("CANDLE_CONTROL", "0", "g_candle_dataset_checks", "INT", ModelInteger((long)g_candle_dataset_checks));
  int count_g_candle_brokers = g_candle_broker_extent;
  if(count_g_candle_brokers < 0 || count_g_candle_brokers > 2048) { ModelFail("CONTINUATION_STATE_CAP"); return; }
  ModelContinuationState("CANDLE_BROKER", "0", "_count", "INT", ModelInteger(count_g_candle_brokers));
  for(int index = 0; index < count_g_candle_brokers; index++)
  {
    ModelContinuationState("CANDLE_BROKER", ModelInteger(index), "active", "BOOL", ModelBoolean(g_candle_brokers[index].active));
    ModelContinuationState("CANDLE_BROKER", ModelInteger(index), "filled", "BOOL", ModelBoolean(g_candle_brokers[index].filled));
    ModelContinuationState("CANDLE_BROKER", ModelInteger(index), "close_pending", "BOOL", ModelBoolean(g_candle_brokers[index].close_pending));
    ModelContinuationState("CANDLE_BROKER", ModelInteger(index), "attempt.id", "TEXT", ModelContinuationHex(g_candle_brokers[index].attempt.id, "STATE:attempt.id"));
    ModelContinuationState("CANDLE_BROKER", ModelInteger(index), "attempt.root_id", "TEXT", ModelContinuationHex(g_candle_brokers[index].attempt.root_id, "STATE:attempt.root_id"));
    ModelContinuationState("CANDLE_BROKER", ModelInteger(index), "attempt.parent_id", "TEXT", ModelContinuationHex(g_candle_brokers[index].attempt.parent_id, "STATE:attempt.parent_id"));
    ModelContinuationState("CANDLE_BROKER", ModelInteger(index), "attempt.pattern", "TEXT", ModelContinuationHex(g_candle_brokers[index].attempt.pattern, "STATE:attempt.pattern"));
    ModelContinuationState("CANDLE_BROKER", ModelInteger(index), "attempt.pattern_direction", "INT", ModelInteger((long)g_candle_brokers[index].attempt.pattern_direction));
    ModelContinuationState("CANDLE_BROKER", ModelInteger(index), "attempt.direction", "INT", ModelInteger((long)g_candle_brokers[index].attempt.direction));
    ModelContinuationState("CANDLE_BROKER", ModelInteger(index), "attempt.generation", "INT", ModelInteger((long)g_candle_brokers[index].attempt.generation));
    ModelContinuationState("CANDLE_BROKER", ModelInteger(index), "attempt.sequence", "INT", ModelInteger((long)g_candle_brokers[index].attempt.sequence));
    ModelContinuationState("CANDLE_BROKER", ModelInteger(index), "attempt.decision_time", "INT", ModelInteger((long)g_candle_brokers[index].attempt.decision_time));
    ModelContinuationState("CANDLE_BROKER", ModelInteger(index), "order", "UINT", StringFormat("%I64u", (ulong)g_candle_brokers[index].order));
    ModelContinuationState("CANDLE_BROKER", ModelInteger(index), "deal", "UINT", StringFormat("%I64u", (ulong)g_candle_brokers[index].deal));
    ModelContinuationState("CANDLE_BROKER", ModelInteger(index), "position_id", "UINT", StringFormat("%I64u", (ulong)g_candle_brokers[index].position_id));
    ModelContinuationState("CANDLE_BROKER", ModelInteger(index), "ticket", "UINT", StringFormat("%I64u", (ulong)g_candle_brokers[index].ticket));
    ModelContinuationState("CANDLE_BROKER", ModelInteger(index), "request_id", "UINT", StringFormat("%I64u", (ulong)g_candle_brokers[index].request_id));
    ModelContinuationState("CANDLE_BROKER", ModelInteger(index), "close_order", "UINT", StringFormat("%I64u", (ulong)g_candle_brokers[index].close_order));
    ModelContinuationState("CANDLE_BROKER", ModelInteger(index), "request_time", "INT", ModelInteger((long)g_candle_brokers[index].request_time));
    ModelContinuationState("CANDLE_BROKER", ModelInteger(index), "close_request_time", "INT", ModelInteger((long)g_candle_brokers[index].close_request_time));
    ModelContinuationState("CANDLE_BROKER", ModelInteger(index), "entry_time", "INT", ModelInteger((long)g_candle_brokers[index].entry_time));
    ModelContinuationState("CANDLE_BROKER", ModelInteger(index), "deadline", "INT", ModelInteger((long)g_candle_brokers[index].deadline));
    ModelContinuationState("CANDLE_BROKER", ModelInteger(index), "next_request_time", "INT", ModelInteger((long)g_candle_brokers[index].next_request_time));
    ModelContinuationState("CANDLE_BROKER", ModelInteger(index), "reference_entry", "FLOAT64", ModelContinuationNumber(g_candle_brokers[index].reference_entry));
    ModelContinuationState("CANDLE_BROKER", ModelInteger(index), "entry", "FLOAT64", ModelContinuationNumber(g_candle_brokers[index].entry));
    ModelContinuationState("CANDLE_BROKER", ModelInteger(index), "sl", "FLOAT64", ModelContinuationNumber(g_candle_brokers[index].sl));
    ModelContinuationState("CANDLE_BROKER", ModelInteger(index), "tp", "FLOAT64", ModelContinuationNumber(g_candle_brokers[index].tp));
    ModelContinuationState("CANDLE_BROKER", ModelInteger(index), "volume", "FLOAT64", ModelContinuationNumber(g_candle_brokers[index].volume));
  }
  int count_g_candle_virtuals = g_candle_virtual_extent;
  if(count_g_candle_virtuals < 0 || count_g_candle_virtuals > 6144) { ModelFail("CONTINUATION_STATE_CAP"); return; }
  ModelContinuationState("CANDLE_VIRTUAL", "0", "_count", "INT", ModelInteger(count_g_candle_virtuals));
  for(int index = 0; index < count_g_candle_virtuals; index++)
  {
    ModelContinuationState("CANDLE_VIRTUAL", ModelInteger(index), "active", "BOOL", ModelBoolean(g_candle_virtuals[index].active));
    ModelContinuationState("CANDLE_VIRTUAL", ModelInteger(index), "trial_id", "TEXT", ModelContinuationHex(g_candle_virtuals[index].trial_id, "STATE:trial_id"));
    ModelContinuationState("CANDLE_VIRTUAL", ModelInteger(index), "attempt_id", "TEXT", ModelContinuationHex(g_candle_virtuals[index].attempt_id, "STATE:attempt_id"));
    ModelContinuationState("CANDLE_VIRTUAL", ModelInteger(index), "lane", "TEXT", ModelContinuationHex(g_candle_virtuals[index].lane, "STATE:lane"));
    ModelContinuationState("CANDLE_VIRTUAL", ModelInteger(index), "direction", "INT", ModelInteger((long)g_candle_virtuals[index].direction));
    ModelContinuationState("CANDLE_VIRTUAL", ModelInteger(index), "rr", "INT", ModelInteger((long)g_candle_virtuals[index].rr));
    ModelContinuationState("CANDLE_VIRTUAL", ModelInteger(index), "entry_time", "INT", ModelInteger((long)g_candle_virtuals[index].entry_time));
    ModelContinuationState("CANDLE_VIRTUAL", ModelInteger(index), "deadline", "INT", ModelInteger((long)g_candle_virtuals[index].deadline));
    ModelContinuationState("CANDLE_VIRTUAL", ModelInteger(index), "entry", "FLOAT64", ModelContinuationNumber(g_candle_virtuals[index].entry));
    ModelContinuationState("CANDLE_VIRTUAL", ModelInteger(index), "sl", "FLOAT64", ModelContinuationNumber(g_candle_virtuals[index].sl));
    ModelContinuationState("CANDLE_VIRTUAL", ModelInteger(index), "tp", "FLOAT64", ModelContinuationNumber(g_candle_virtuals[index].tp));
    ModelContinuationState("CANDLE_VIRTUAL", ModelInteger(index), "volume", "FLOAT64", ModelContinuationNumber(g_candle_virtuals[index].volume));
  }
}

#endif
