//+------------------------------------------------------------------+
//|                                    microservices/core/enums.mqh  |
//+------------------------------------------------------------------+
#ifndef _MICROSERVICES_CORE_ENUMS_MQH_
#define _MICROSERVICES_CORE_ENUMS_MQH_

enum SignalTypes
{
  NO_SIGNAL = 0,
  BULLISH   = 1,
  BEARISH   = 2
};

enum StrategyDirectionTypes
{
  BOTH_DIRECTION    = 0,
  BULLISH_DIRECTION = 1,
  BEARISH_DIRECTION = 2
};

enum PivotHftCampaignStatuses
{
  PIVOT_HFT_CAMPAIGN_IDLE       = 0,
  PIVOT_HFT_CAMPAIGN_ARMED      = 1,
  PIVOT_HFT_CAMPAIGN_TRACKING   = 2,
  PIVOT_HFT_CAMPAIGN_ORDER_WAIT = 3,
  PIVOT_HFT_CAMPAIGN_EXPIRED    = 4,
  PIVOT_HFT_CAMPAIGN_COMPLETED  = 5
};

enum PivotHftPositionStatuses
{
  PIVOT_HFT_POSITION_ACTIVE     = 0,
  PIVOT_HFT_POSITION_CLOSE_WAIT = 1,
  PIVOT_HFT_POSITION_CLOSED     = 2,
  PIVOT_HFT_POSITION_COMPLETED  = 3
};

enum PivotHftPivotLevels
{
  PIVOT_HFT_LEVEL_NONE = 0,
  PIVOT_HFT_LEVEL_P    = 1,
  PIVOT_HFT_LEVEL_R1   = 2,
  PIVOT_HFT_LEVEL_R2   = 3,
  PIVOT_HFT_LEVEL_R3   = 4,
  PIVOT_HFT_LEVEL_S1   = 5,
  PIVOT_HFT_LEVEL_S2   = 6,
  PIVOT_HFT_LEVEL_S3   = 7
};

enum PivotHftCloseTriggers
{
  PIVOT_HFT_CLOSE_TRIGGER_NONE       = 0,
  PIVOT_HFT_CLOSE_TRIGGER_INITIAL_SL = 1,
  PIVOT_HFT_CLOSE_TRIGGER_BREAK_EVEN = 2,
  PIVOT_HFT_CLOSE_TRIGGER_TRAILING   = 3,
  PIVOT_HFT_CLOSE_TRIGGER_EXTERNAL   = 4,
  PIVOT_HFT_CLOSE_TRIGGER_FIXED_TP   = 5,
  PIVOT_HFT_CLOSE_TRIGGER_ENTRY_SAFETY = 6,
  PIVOT_HFT_CLOSE_TRIGGER_REGISTRATION_FAILURE = 7,
  PIVOT_HFT_CLOSE_TRIGGER_RECOVERY_FAILURE = 8
};

enum PivotHftNetClasses
{
  PIVOT_HFT_NET_NONE   = 0,
  PIVOT_HFT_NET_PROFIT = 1,
  PIVOT_HFT_NET_LOSS   = 2,
  PIVOT_HFT_NET_FLAT   = 3
};

enum DailySignalLimitModes
{
  STOP_DAILY_SIGNALS         = 0,
  STOP_DAILY_SIGNALS_ON_LOSS = 1
};

enum SessionTimeFilterModes
{
  SESSION_FILTER_OFF         = 0,
  SESSION_FILTER_ALLOW_RUN   = 1,
  SESSION_FILTER_FORCE_CLOSE = 2
};

enum SessionTimeFilterSlots
{
  SESSION_TIME_FILTER_ASIA    = 0,
  SESSION_TIME_FILTER_LONDON  = 1,
  SESSION_TIME_FILTER_NEWYORK = 2
};

#define SESSION_TIME_FILTER_SLOT_TOTAL 3

enum DstOffsetModes
{
  DST_MODE_OFF         = 0,
  DST_MODE_AUTO_EXNESS = 1,
  DST_MODE_MANUAL      = 2
};

enum ProtectionRiskModes
{
  PROTECTION_DISABLED    = 0,
  PROTECTION_ACTIVE      = 1,
  PROTECTION_DAILY_LOCK  = 2,
  PROTECTION_WEEKLY_LOCK = 3
};

enum ProtectionRiskValueTypes
{
  PROTECTION_RISK_ACCOUNT_SIZE_PERCENT    = 0,
  PROTECTION_RISK_ACCOUNT_BALANCE_PERCENT = 1,
  PROTECTION_RISK_FIXED_CURRENCY           = 2
};

enum MarketStatusTypes
{
  MARKET_STATUS_ACTIVE            = 0,
  MARKET_STATUS_CLOSE_GUARD       = 1,
  MARKET_STATUS_BROKER_CLOSEONLY  = 2,
  MARKET_STATUS_BROKER_DISABLED   = 3,
  MARKET_STATUS_PLATFORM_DISABLED = 4
};

#endif // _MICROSERVICES_CORE_ENUMS_MQH_
