// Generated by tools.model_dataset.continuation_contract; do not edit.
#ifndef MODEL_CONTINUATION_SCHEMA_MQH
#define MODEL_CONTINUATION_SCHEMA_MQH
const string MODEL_CONTINUATION_DIGEST = "d29647a3f1f44fb72fde615d1ec0d358dafe0d6eef6ff150a0568cf90a1f22e4";
const string MODEL_CONTINUATION_SOURCE_SHA256 = "eff52334565416511d540fd4dbd739d6aa349ba709c2118452faf8c7f502ac30";
enum { MODEL_CONTINUATION_FILE_COUNT = 6, MODEL_CONTINUATION_INPUT_WIDTH = 36, MODEL_CONTINUATION_TRANSACTION_WIDTH = 44 };
string ModelContinuationFilename(const int file)
{
  switch(file)
  {
    case 0: return "segment_manifest.tsv";
    case 1: return "input_events.tsv";
    case 2: return "fact_events.tsv";
    case 3: return "window_births.tsv";
    case 4: return "state_checkpoint.tsv";
    case 5: return "segment_seal.tsv";
  }
  return "";
}
string ModelContinuationHeader(const int file)
{
  switch(file)
  {
    case 0: return "key\tvalue";
    case 1: return "record_ordinal\tfirst_input_ordinal\tlast_input_ordinal\tboundary_callback\tfirst_broker_time_msc\tlast_broker_time_msc\tfirst_observer_time_msc\tobserver_time_msc\tfirst_monotonic_us\tmonotonic_us\tinput_count\tavailable_count\tunavailable_count\ttick_count\ttimer_count\ttrade_count\tinput_chain_sha256\tquote_hex\tconnected\tsynchronized\tacquisition\ttransaction_hex\tmaximum_quote_age_msc\tlast_quote_age_msc\tbroker_estimate_time_msc\thistory_observations\thistory_chain_sha256\tmaximum_observer_gap_msc\tmaximum_monotonic_gap_us\tcapture_status\tquote_status\tfresh_quote_count\tstale_quote_count\tmissing_quote_count\tstale_tick_count\tstale_trade_count";
    case 2: return "fact_ordinal\tinput_ordinal\tphase\ttable_name\trow_key\tpayload_hex";
    case 3: return "birth_ordinal\tinput_ordinal\twindow_id\topen_time_msc\tsource_time_msc\tsource_close_time_msc\tmacro_seconds\tsource_open\tsource_high\tsource_low\tsource_close\tvalid\treason\traw_prices_hex\ttrade_prices_hex\tfirst_observed_time_msc\tfirst_observed_bid";
    case 4: return "boundary\tcomponent\tobject_id\tfield\tvalue_type\tvalue";
    case 5: return "key\tvalue";
  }
  return "";
}
string ModelContinuationRowKey(const int file)
{
  switch(file)
  {
    case MODEL_MACRO_WINDOWS: return "window_id";
    case MODEL_SIGNAL_EVENTS: return "signal_id";
    case MODEL_FEATURE_SNAPSHOTS: return "snapshot_id";
    case MODEL_ENTRY_ATTEMPTS: return "attempt_id";
    case MODEL_TRIALS: return "trial_id";
    case MODEL_EXECUTION_CHECKS: return "check_id";
    case MODEL_OUTCOMES: return "trial_id";
    case MODEL_PIVOT_ORIGINS: return "signal_id";
    case MODEL_CANDLE_SIGNALS: return "signal_id";
    case MODEL_CANDLE_ATTEMPTS: return "attempt_id";
  }
  return "";
}
string ModelContinuationWitnessFilename(const int index)
{
  switch(index)
  {
    case 0: return "witness_manifest.tsv";
    case 1: return "input_prefix.tsv";
    case 2: return "fact_prefix.tsv";
    case 3: return "window_prefix.tsv";
    case 4: return "state_checkpoint.tsv";
    case 5: return "witness_seal.tsv";
  }
  return "";
}
string ModelContinuationWitnessManifestKey(const int index)
{
  switch(index)
  {
    case 0: return "family";
    case 1: return "version";
    case 2: return "descriptor_sha256";
    case 3: return "engine";
    case 4: return "origin";
    case 5: return "source_id";
    case 6: return "session_id";
    case 7: return "source_proof";
    case 8: return "configuration_proof";
    case 9: return "history_proof";
    case 10: return "core_manifest_sha256";
    case 11: return "last_input_ordinal";
    case 12: return "last_fact_ordinal";
    case 13: return "last_birth_ordinal";
    case 14: return "predecessor_seal";
    case 15: return "anchor_state_sha256";
    case 16: return "end_state_sha256";
    case 17: return "legacy_source_proof";
    case 18: return "native_fence_proof";
  }
  return "";
}
string ModelContinuationWitnessSealKey(const int index)
{
  switch(index)
  {
    case 0: return "rows_witness_manifest.tsv";
    case 1: return "bytes_witness_manifest.tsv";
    case 2: return "chain_witness_manifest.tsv";
    case 3: return "rows_input_prefix.tsv";
    case 4: return "bytes_input_prefix.tsv";
    case 5: return "chain_input_prefix.tsv";
    case 6: return "rows_fact_prefix.tsv";
    case 7: return "bytes_fact_prefix.tsv";
    case 8: return "chain_fact_prefix.tsv";
    case 9: return "rows_window_prefix.tsv";
    case 10: return "bytes_window_prefix.tsv";
    case 11: return "chain_window_prefix.tsv";
    case 12: return "rows_state_checkpoint.tsv";
    case 13: return "bytes_state_checkpoint.tsv";
    case 14: return "chain_state_checkpoint.tsv";
  }
  return "";
}
#endif
