#ifndef _SERVICES_TRADING_SIGNALS_EXECUTION_PRICE_RESOLVER_MQH_
#define _SERVICES_TRADING_SIGNALS_EXECUTION_PRICE_RESOLVER_MQH_

// Relies on the include cascade to provide SignalParams, ExecutionLegState, etc.

#endif // _SERVICES_TRADING_SIGNALS_EXECUTION_PRICE_RESOLVER_MQH_
